// apps/web/lib/clinical/models/enums.ts

export enum ReportStatus {
  DRAFT = "DRAFT",
  GENERATED = "GENERATED",
  UNDER_REVIEW = "UNDER_REVIEW",
  PATHOLOGIST_APPROVED = "PATHOLOGIST_APPROVED",
  PUBLISHED = "PUBLISHED",
  DELIVERED = "DELIVERED",
  ACKNOWLEDGED = "ACKNOWLEDGED",
  ARCHIVED = "ARCHIVED",
}

export enum AlertSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  CRITICAL = "CRITICAL",
}

export enum AlertType {
  CRITICAL_VALUE = "CRITICAL_VALUE",
  REPEATED_ABNORMAL = "REPEATED_ABNORMAL",
  MISSING_FOLLOWUP = "MISSING_FOLLOWUP",
  HIGH_RISK_TREND = "HIGH_RISK_TREND",
}

export enum TrendDirection {
  UPWARD = "UPWARD",
  DOWNWARD = "DOWNWARD",
  STABLE = "STABLE",
  CRITICAL_SPIKE = "CRITICAL_SPIKE",
}

export enum ReferenceRangeType {
  NORMAL = "NORMAL",
  DESIRABLE = "DESIRABLE",
  BORDERLINE = "BORDERLINE",
  HIGH_RISK = "HIGH_RISK",
  CRITICAL = "CRITICAL",
}

export enum KnowledgeCategory {
  PATHOLOGY = "PATHOLOGY",
  RADIOLOGY = "RADIOLOGY",
  CARDIOLOGY = "CARDIOLOGY",
  GENOMICS = "GENOMICS",
  PREVENTIVE = "PREVENTIVE",
}

export enum ShareType {
  PATIENT_VAULT = "PATIENT_VAULT",
  DOCTOR_DIRECT = "DOCTOR_DIRECT",
  FAMILY_TEMPORARY = "FAMILY_TEMPORARY",
  EXPIRING_LINK = "EXPIRING_LINK",
}

export enum ApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  AMENDED = "AMENDED",
}

export enum SignatureStatus {
  UNSIGNED = "UNSIGNED",
  DIGITALLY_SIGNED = "DIGITALLY_SIGNED",
  INVALIDATED = "INVALIDATED",
}
