// apps/web/lib/operations/models/enums.ts

export enum AlertSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  CRITICAL = "CRITICAL",
}

export enum AlertType {
  SLA_BREACH = "SLA_BREACH",
  TECHNICIAN_OFFLINE = "TECHNICIAN_OFFLINE",
  PARTNER_CAPACITY_OVERLOAD = "PARTNER_CAPACITY_OVERLOAD",
  EXPRESS_DISPATCH_FAILURE = "EXPRESS_DISPATCH_FAILURE",
  PROCESSING_DELAY = "PROCESSING_DELAY",
  SYSTEM_HEALTH = "SYSTEM_HEALTH",
}

export enum SLAStatus {
  GREEN = "GREEN",
  YELLOW = "YELLOW",
  RED = "RED",
}

export enum ExceptionType {
  NO_SHOW = "NO_SHOW",
  FAILED_COLLECTION = "FAILED_COLLECTION",
  SAMPLE_REJECTED = "SAMPLE_REJECTED",
  DELAYED_TECHNICIAN = "DELAYED_TECHNICIAN",
  PARTNER_CAPACITY_FULL = "PARTNER_CAPACITY_FULL",
  COURIER_DELAY = "COURIER_DELAY",
  LATE_REPORT = "LATE_REPORT",
  MANUAL_ESCALATION = "MANUAL_ESCALATION",
}

export enum ExceptionSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ExceptionStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  ESCALATED = "ESCALATED",
}

export enum ShiftStatus {
  SCHEDULED = "SCHEDULED",
  ON_DUTY = "ON_DUTY",
  COMPLETED = "COMPLETED",
  ON_LEAVE = "ON_LEAVE",
  ABSENT = "ABSENT",
}

export enum RegionZone {
  HYDERABAD_CENTRAL = "HYDERABAD_CENTRAL",
  HYDERABAD_CYBERABAD = "HYDERABAD_CYBERABAD",
  BANGALORE_EAST = "BANGALORE_EAST",
  BANGALORE_SOUTH = "BANGALORE_SOUTH",
  MUMBAI_WEST = "MUMBAI_WEST",
  DELHI_NCR = "DELHI_NCR",
}
